### ISSUE TITLE
Multi layouts for pages

### ISSUE THREAD

**Issue by dominikwilkowski** [saclark/jekyll-multipost#1]
Hey there,

Great plugin but I need it to work on pages as well. Is there a way?

**Comment by saclark** [comment]
Thanks! I'm glad you've found it useful. Am I correct in understanding that you are wondering if it will work on GitHub Pages? If that is the case then no, you will not be able to use it because GitHub Pages does not allow custom plugins for security reasons.

However, the [Jekyll docs](http://jekyllrb.com/docs/plugins/) do mention a workaround, where you could:

> convert the site locally and push the generated static files to your GitHub repository instead of the Jekyll source files.

**Comment by dominikwilkowski** [comment]
Hey there,

No not GitHub pages ;)
I mean on pages rather than blog posts.

**Comment by saclark** [comment]
Ah, gotcha, good idea! I've added the feature. Please let me know if you find any bugs or have any issues with it.

Also, I've updated the docs in the README and added support for defining permalinks for the generated posts (or pages) via a `:layout` ulr template variable.

**Comment by dominikwilkowski** [comment]
works great!
Thanks
