### ISSUE TITLE
Adding `multipost` to Jekyll gems causes error; plus support for collections

### ISSUE THREAD

**Issue by nfreear** [saclark/jekyll-multipost#2]
Hi Scott / @saclark,
First, thank you for the v. useful plugin!

I'm not a Ruby developer, so this issue may well be a mis-understanding on my part ...
- I've copied the `multipost.rb` file to the `_plugins` directory;
- I've also added it to the `_config.yml` file -- is this necessary?

``` yaml
gems:
  - json
  - yaml
  - multipost
```

This gives an error:

```
Configuration file: /Users/Nick/workspace/accessify-wiki-fixes/_config.yml
/usr/local/Cellar/ruby/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require': cannot load such file -- multipost (LoadError)
    from /usr/local/Cellar/ruby/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
    from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:29:in `block in require_gems'
    from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `each'
...
```

However, not adding it to `_config.yml` seems to generate this warning:

```
Regenerating: 1 file(s) changed at 2016-01-23 11:10:46      Build Warning: Layout '["fix", "fix-json"]' requested in _fixes/ou-news.md does not exist.
```

I'm trying to use the plugin with a Jekyll `collection`, and I've just realised that the plugin may not yet support collections!

Thanks for your time,

Nick

**Comment by saclark** [comment]
@nfreear Thanks, I'm glad you've found it useful!

This plugin is not available as a gem (i.e. it is not available for download via the RubyGems package manager), although I may make it a gem someday. In order to use this plugin, the only thing you have to do is place the `multipost.rb` file in your `_plugins` directory and you should be good to go (option 1 here: http://jekyllrb.com/docs/plugins/). You received that first error you posted because you added it to your list of gems in `_config.yml` but this plugin is not available as a gem, so when your code tried to `require` it, it failed because it could not find such a gem.

Regarding the second error you posted, it appears my plugin does not yet work with collections. I admit I have not used Jekyll in a long time and was not aware they added the collections feature so thanks for letting me know about this. When I find some time, I will try to take a look and see if I can add support for collections. However, given that collections are still an experimental feature of Jekyll, if I do add support, it will probably be in a separate branch that you can download and try. I'll wait for the collections feature to stabilize before merging any support into master.

If/when I do add support for collections, I'll let you know here.

**Comment by saclark** [comment]
@nfreear Finally found some time to dig into this an it appears my current implementation breaks when used with Jekyll version 3+. I've committed a `jekyll-3` branch where I'm working on an implementation that works with Jekyll 3.x.x, including support for rendering collection items in multiple layouts.

The code in the `jekyll-3` branch is a very hacky first iteration to try and see if I could get things working, which I believe I did. Please feel free to download that branch and try it out, as I believe it should do what you need (for now) but please know that **it is in need of some serious refactoring** which I am planning to do as I find time. Once I am done refactoring and we are happy with the result, I will close this ticket.

**Comment by saclark** [comment]
closing this issue since my latest push should address these issues.
